---
- hosts: container
  become: true
  become_user: root
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

   tasks:
     # Example just get information about the repository whether or not it has
     # already been cloned locally.
     - git:
         repo: 'https://github.com/centos2011/ansible/repo.git'
         dest: /srv/checkout
         clone: no
         update: no
