- hosts: rhel6servers
  tasks:
  #Copy a new "/home/admindj/ into place, backing up the original if it differs from the copied version
  - copy:
      src: /home/admindj/repository/ansible/src/.bash_profile
      dest: /home/admindj/.bash_profile
      owner: admindj
      #group: root
      #mode: 0644
      backup: yes
