- hosts: rhel6servers
  become: true
  become_user: root
  tasks:
  #Copy a new "/etc/environment file into place, backing up the original if it differs from the copied version
  - copy:
      src: /home/admindj/repository/ansible/src/environment
      dest: /etc/environment
      owner: root
      group: root
      mode: 0644
      backup: yes
