---
- hosts: csp-pd
  tasks:
    - name: restart server
      shell: sleep 2 && /sbin/shutdown -r now "Ansible shutdown server triggered"
      async: 1
      poll: 0
      become: true
      become_user: root
      ignore_errors: true

    - name: wait for server {{ ansible_ssh_host | default(inventory_hostname) }} to come back online
      wait_for:
        port: 22
        state: started
        host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
        delay: 30
      delegate_to: localhost
