- hosts: rhel6servers
  become: true
  become_user: root
  tasks:
      - name: Register RHEL6 as user rhel_admin@champ.aero credentials and auto-subscribe.
        redhat_subscription:
          state: present
          username: rhel_admin@champ.aero #change with the correct username
          password: RHEL4champ$ #change with the correct password
          autosubscribe: yes
