- hosts: csp-ipa-enroll
  become: true
  become_user: root
  tasks:
  #Copy a new "resolv.conf file into place, backing up the original if it differs from the copied version
  - copy:
      src: /home/admindj/repository/ansible/src/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
