---
- name: create some vms
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "vcenter_host"
      prompt: "Enter vcenter host"
      private: no
      default: "cs-v-vcenter-mnl"
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
      default: "root"
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes
    - name: "vcenter_datacenter"
      prompt: "Enter datacenter name"
      private: no
      deafult: "MNLFarm"
    - name: "vcenter_datastore"
      prompt: "Enter datastore name"
      private: no
      default: "DASMNL01-Disk1"
    - name: "esxi_host"
      prompt: "Enter vsphere host"
      private: no
      default: "esxmnl01"
  vars:
#    - vcenter_folder: 'TASMNL'
    - vms:
        - guest: 'cs-v-jenkins-mnl-t2'
          state: 'powered_on'
          vcpu_hotadd: 'yes'
          mem_hotadd: 'yes'
          notes: 'Ansible Created'
          num_disks: '1'
          disks:
            disk1:
              size_gb: '10'
              type: 'thin'
          network: 'VM Network'
          memory: '4096'
          cpus: '1'
          osid: 'rhel6_64Guest'
  tasks:
    - name: create vms (Single Disk)
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ item.guest }}"
        state: "{{ item.state }}"
        vm_extra_config:
          vcpu.hotadd: "{{ item.vcpu_hotadd|default(omit) }}"
          mem.hotadd: "{{ item.mem_hotadd|default(omit) }}"
          notes: "{{ item.notes|default(omit) }}"
##         folder: "{{ vcenter_folder }}"
#        vm_disk:
#          disk1:
#            size_gb: "{{ item.disks.disk1.size }}"
#            type: "{{ item.disks.disk1.type }}"
#            datastore: "{{ vcenter_datastore }}"
##          folder: "{{ vcenter_folder }}"
#        vm_nic:
#          nic1:
#            type: "vmxnet3"
#            network: "{{ item.network }}"
#            network_type: "standard"
#        vm_hardware:
#          memory_mb: "{{ item.memory }}"
#          num_cpus: "{{ item.cpus }}"
#          osid: "{{ item.osid }}"
#          scsi: "paravirtual"
#          vm_cdrom:
#            type: "iso"
#            iso_path: "NASMNL01/ISO/Linux/CentOS/CentOS-7-x86_64-Minimal-1708.iso"
#        esxi:
#          datacenter: "{{ vcenter_datacenter }}"
#          hostname: "{{ esxi_host }}"
#      with_items: vms
#      when: item.num_disks == '1'
