- hosts: test-server
  become: true
  become_user: root
  tasks:
      - name: Register RHEL6 as user rhel_admin@champ.aero credentials and auto-subscribe.
        redhat_subscription:
          state: present
          username: rhel_admin@champ.aero
          password: RHEL4champ$
          autosubscribe: yes
