- hosts: csp-demo-server
  become: true
  become_user: root
  tasks:
      - name: Register RHEL7 as rhel_admin@champ.aero credentials and auto-subscribe.
        redhat_subscription:
          state: present
          username: user
          password: password
          autosubscribe: yes
